# transformer metrics
metrics:
  - class: LossMetricSpec
    params:
      start_at: 0
      eval_steps: 100
      batch_size: 64

  - class: BleuMetricSpec
    params:
      start_at: 10000
      eval_steps: 1000
      batch_size: 32
      beam_size: 10
      length_penalty: -1.0
      delimiter: " "
      char_level: false
      maximum_keep_models: 5
      early_stop: true